name: Deploy to Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  check_merge_from_dev:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check if PR is merged from dev
        id: check
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && \
                "${{ github.event.pull_request.head.ref }}" == "dev" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: [self-hosted, vps-deploy]
    needs: [check_merge_from_dev]
    if: needs.check_merge_from_dev.outputs.should_run == 'true'
    steps:
      - name: Deploy to Production
        run: |
          flock -x /tmp/qsmart-deploy.lock \
            sudo /usr/bin/bash /root/servers/QSMART-SERVER/scripts/deploy.sh
